# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-15 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rsvp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_attending', models.BooleanField(default=True)),
                ('num_attending', models.IntegerField(default=0)),
                ('num_steak', models.IntegerField(default=0)),
                ('num_fish', models.IntegerField(default=0)),
            ],
        ),
    ]
