# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-15 03:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rsvp',
            name='is_brunch',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='num_children',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rsvp',
            name='num_vegetarian',
            field=models.IntegerField(default=0),
        ),
    ]
